scrape_configs:
  - job_name: 'helidon_metrics'

    static_configs:
      - targets: ['helidon-example-metrics:8080']

    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']
